### ISSUE TITLE
Loading External Image

### ISSUE THREAD

**Issue by brianpmarks** [trinketapp/processing.sk#35]
Forgive me if this is known but a [user reported](https://app.intercom.io/a/apps/eezvdz15/respond/inbox/conversation/14089458931) that loading external images is no longer working and produces an error: "ExternalError: TypeError: Cannot read property 'ignored' of undefined on line 57 in main.py"

The above error can be seen in this example: https://trinket.io/embed/python/413874d92c

**Comment by eah13** [comment]
Ah.  A fix for this is on master (#31) but didn't get its own release because, if I remember correctly, we were expecting #33 to be merged soon after.  Updating the release should resolve the error here, which is due to the second arg in `loadImage`

That's not all that's at play, I don't think, since removing the second args in this trinket produces a blank, errorless trinket https://trinket.io/python/3b9f740f3a

Unless proven otherwise, I believe this is thus equivalent with #36.  Closing in favor of that until then.
